name: My CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  terraformec2:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0
      - name: Ini Terraform
        run: terraform init
      - name: Apply Terraform
        run: terraform apply --auto-approve
    configureec2ansible:
      runs-on: ubuntu-latest
      steps:
       - name: Install Ansible
         run: sudo apt-get update && sudo apt-get install -y ansible
       - name: Configure EC2
         run: ansible-playbook -i ansible/inventory.yml ansible/playbook.yml
      compile:
        runs-on: ubuntu-latest
        steps:
         - name: Compile Application
           run: go build -o main myapp/main.go
        buildandpush:
          runs-on: ubuntu-latest
          steps:
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/webui
          deploy:
               runs-on: ubuntu-latest
               steps:    
                 - name: Deploy Application to EC2 instance
                   run: ansible-playbook -i ansible/inventory.yml ansible/deploy.yml
